### ISSUE TITLE
Test in docker

### ISSUE THREAD

**Issue by 0xlukaC** [0xlukaC/celp#3]
I attempted to write CI with Github actions for testing, however, it didn't seem to work due to the way pathing works in a docker environment. Below are the details of the yml configuration and suggested changes for test.c.

yml file for Github actions:
```yml
name: test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install GCC and Valgrind
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc valgrind

    - name: Ensure test_script.sh is executable
      run: chmod +x ./testing/test_script.sh

    - name: Compile test.c
      run: gcc testing/test.c -o test

    - name: Run test
      run: ./test
    # - name: Run Valgrind
    #   run: valgrind ./test
```
Furthermore, if you want it to work, you have to change `http://localhost:<port>` to `http://127.0.0.1:<port>`
and in test.c you have to provide this code:
```c
int main() {
  char cwd[512];
  if (getcwd(cwd, sizeof(cwd)) != NULL) {
    printf("Current working directory: %s\n", cwd);
  } else {
    perror("getcwd() error");
  }
  if (!strstr(cwd, "testing")) {
    snprintf(cwd, 532, "%s/testing", cwd);
  }

// ...
char bashfile[1024];
snprintf(bashfile, 1024, "%s/test_script.sh", cwd);
int shres = system(bashfile);
// ...
```

Output from Github actions:
```
Run ./test

Testing http://127.0.0.1:8001/example.html w/ [4](https://github.com/0xlukaC/celp-test/actions/runs/12633678082/job/35199789561#step:6:5)04 & text/html...
No filepath provided anywhere for /example.html


Testing http://12[7](https://github.com/0xlukaC/celp-test/actions/runs/12633678082/job/35199789561#step:6:8).0.0.1:[8](https://github.com/0xlukaC/celp-test/actions/runs/12633678082/job/35199789561#step:6:9)001/asdf* ///gArBage/ w/ 404 & null...


Testing http://[12](https://github.com/0xlukaC/celp-test/actions/runs/12633678082/job/35199789561#step:6:13)7.0.0.1:8001/public/files/file1.txt w/ null & null...

Testing http://127.0.0.1:8001/testing/public/image.jpg w/ 200 & null...
./testing/test_script.sh: line 21: echo: write error: Broken pipe
Test failed: Expected status '200', got something else.
Current working directory: /home/runner/work/celp-test/celp-test
Hello, World!
Key: /testing/public/image.jpg
Path: testing/public/image.jpg
Key: / is not a regular file
Key: /public/files/* is not a regular file
Key: /public/files/* is not a regular file
Key: /login is not a regular file
 -> / 
/ -> ./index.txt 
/asdf* ///gArBage/ ->  
/login -> (null) 
/public/files/* -> (null) 
/public/files/file1.txt -> ./public/files/file1.txt 
/testing/public/image.jpg -> testing/public/image.jpg 
Script exit status: 1
Error: Process completed with exit code 1.
````
